name: stringreverse
version: 0.0.1
description: >
  A general purpose string reverse extension on Dart.
author: Michael John Peña <mjtpena@outlook.com>
homepage: https://github.com/mjtpena/stringreverse.dart
environment:
  sdk: ">=1.0.0 <3.0.0"
dependencies:
  convert: ">=1.0.0 <3.0.0"
dev_dependencies:
  test: any
